spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flick
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20

  kafka:
    bootstrap-servers: localhost:9092