services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: flick
      POSTGRES_PASSWORD: pqlamz!!
      POSTGRES_DB: flick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flick-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - flick-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - flick-network

  api-gateway:
    build:
      context: ./api-gateway
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - flick-network
    depends_on:
      - admin-service
      - place-service

  service-registry:
    build:
      context: ./service-registry
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: service-registry
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8761:8761"
    networks:
      - flick-network

  admin-service:
    build:
      context: ./admin-service
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: admin-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - flick-network
    depends_on:
      - kafka
      - postgres
      - service-registry

  place-service:
    build:
      context: ./place-service
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: place-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - flick-network
    depends_on:
      - kafka
      - postgres
      - service-registry

volumes:
  postgres_data:

networks:
  flick-network:
    driver: bridge