services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: flick
      POSTGRES_PASSWORD: pqlamz!!
      POSTGRES_DB: flick
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  service-registry:
    build:
      context: ./service-registry
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: service-registry
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8761:8761"

  place-redis:
    image: redis:latest
    container_name: place-redis
    ports:
      - "6380:6379"

volumes:
  postgres_data: