server:
  port: 8080

spring:
  application:
    name: flick-api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: place-service
          uri: http://place-service:8080
          predicates:
            - Path=/place/**
          filters:
            - StripPrefix=1
        - id: place-service-ws
          uri: ws://place-service:8080
          predicates:
            - Path=/place/ws/**
          filters:
            -  StripPrefix=1

        - id: core-service
          uri: http://core-service:8080
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: http://admin-service:8080
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
      default-filters:
        - AddResponseHeader=Cache-Control, no-cache

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/