spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/flick
    username: flick
    password: pqlamz!!

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

server:
  port: 8080