spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/flick
    username: flick
    password: pqlamz!!

  data:
    redis:
      host: place-redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/