spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flick
    username: flick
    password: pqlamz!!

  data:
    redis:
      host: localhost
      port: 6380

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

logging:
  level:
    org.springframework.r2dbc.core: debug