spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/flick
    username: flick
    password: pqlamz!!

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

logging:
  level:
    com.flick: DEBUG
