spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/flick
    username: flick
    password: pqlamz!!

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
